### PR TITLE
add a setup script and requirements file for install

### PR DESCRIPTION
**Pull request by hmenager**
This PR is to propose the addition of a setup script to ldsc. It would make it easier to install ldsc. Thank you for considering it!

### CODE REVIEW

**Comment by hmenager** [comment]
poking this. I packaged ldsc for bioconda using that setup script, but if the PR were to be merged in that repo it would allow me to remove the "patching" of ldsc and ease its distribution. thank you!

**Comment by tpoterba** [comment]
The setup.py should pin versions of its dependencies, right?

There's no guarantee that a dependency with a major version different from the environment.yml in the repository will work with LDSC.

**Comment by hmenager** [comment]
I agree with you. dependency versions should be a little more constrained than this (although probably not pinned to specific versions, to allow for bug corrections in the dependencies).  I'll modify my PR

**Comment by hmenager** [comment]
(specific versions are already pinned in the pip `requirements.txt` file)

**Comment by hmenager** [comment]
ok done, it looks like this is working. thanks for your review @tpoterba

**Comment by tpoterba** [comment]
great, thanks for the contribution!

**Pull request merged**
